platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((proget-docker-registry.url))/docker/ubuntu
    tag: 20.04
    username: ((proget-docker-registry.username))
    password: ((proget-docker-registry.password))

outputs:
- name: workspace
- name: project-metadata

inputs:
- name: nexus-repo
- name: dockerfile_repo
- name: pipeline_repo

run:
  path: /bin/bash
  args:
  - -c
  - |
    output_dir=workspace

    if [ -z "$docker_location" ]; then
      echo "ERROR: No dockerfile location provided"
      exit 1
    fi

    if [ -z "$jar_name" ]; then
      jar_name=app.jar
    fi

    # Create version file if specified
    if [ -n "$tag" ]; then
      echo "$tag" > ./project-metadata/version
    fi

    cp ./dockerfile_repo/$docker_location/* "${output_dir}/"
    cp ./nexus-repo/*.jar "${output_dir}/$jar_name"
    chmod +x ${output_dir}/$jar_name
